name: Build and Deploy LaTeX Resume

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: AryanAnandResume.tex

    - name: Move PDF to docs folder
      run: |
        mkdir -p docs
        mv AryanAnandResume.pdf docs/

    - name: Commit and push PDF with PAT
      env:
        PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "aryan-212"
        git config --global user.email "73695300+aryan-212@users.noreply.github.com"
        git add docs/*.pdf
        git commit -m "Add built PDF" || echo "No changes to commit"
        git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:main
